In [2]:
from sentence_transformers import SentenceTransformer, util
encoder = SentenceTransformer("sentence-transformers/gtr-t5-base")

Error while downloading from https://cdn-lfs.huggingface.co/sentence-transformers/gtr-t5-base/09fb3d444f67e758ee202396e36971d94d6da970f0283fd21b9c1348f361bcb4?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1713002900&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzAwMjkwMH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvZ3RyLXQ1LWJhc2UvMDlmYjNkNDQ0ZjY3ZTc1OGVlMjAyMzk2ZTM2OTcxZDk0ZDZkYTk3MGYwMjgzZmQyMWI5YzEzNDhmMzYxYmNiND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=vOwNwqWjTUKdck6m1oli-lnjKD0MRY8QTXlvgVKDz%7E0cdfNho-IbtBgf5ikmezmRxy51VG5gOvecJ0uDC4pjJmr5V1UzG%7EoV1ujAFOyO-tOnQnswmRc-GvlxPAgTmoHDSXznLb%7ENdXwULf0MVKJHu97-CbBjytUE-VgaQUA0ey5gb7iqlf-niKkCN69JqgcPiGhkVKB8nm043BeLblPvIbY4vcJaPH9G7B%7Ephvj5gspmgFFAYTnP-z6ljE63HB9QdZu%7EhKWV-C6l6H0ugw6lKrVIXw%7EhUKUXA3ZlhWaqWWqEm0El0KJVKQ4JLZJxnLp6pWeg2Mne7TJT4vh

In [3]:
encoder

SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': False}) with Transformer model: T5EncoderModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Dense({'in_features': 768, 'out_features': 768, 'bias': False, 'activation_function': 'torch.nn.modules.linear.Identity'})
  (3): Normalize()
)

In [6]:
tokenizer = encoder.tokenizer
text = "Ala ma kota"
enc_text = tokenizer.encode(text)
enc_text

[901, 9, 954, 3, 15414, 9, 1]

In [7]:
vocab = tokenizer.vocab
inv_vocab = {v: k for k,v in vocab.items()}
tokens = [inv_vocab[item] for item in enc_text]
tokens

['▁Al', 'a', '▁ma', '▁', 'kot', 'a', '</s>']

In [8]:
def get_tokens(text):
    enc_text = tokenizer.encode(text)
    tokens = [inv_vocab[item] for item in enc_text]
    return tokens

sentences = ["abcd", "xdddd", "pare roznych slow oraz zdan", "and something in english :D"] 
sentences_tokens = [get_tokens(text) for text in sentences]
sentences_tokens   

[['▁ab', 'c', 'd', '</s>'],
 ['▁', 'x', 'd', 'd', 'd', 'd', '</s>'],
 ['▁pare',
  '▁',
  'roz',
  'n',
  'ych',
  '▁slow',
  '▁or',
  'a',
  'z',
  '▁',
  'z',
  'dan',
  '</s>'],
 ['▁and', '▁something', '▁in', '▁english', '▁', ':', 'D', '</s>']]

In [12]:
tokens = list(vocab.keys())
tokens

['▁vehicul',
 '▁relaxation',
 '▁comisi',
 '▁purta',
 'EVER',
 '▁Guide',
 'östlich',
 '▁Ga',
 '▁penetration',
 '▁Uhr',
 'car',
 '▁slim',
 '▁kostenfrei',
 '▁Alege',
 'tür',
 '▁propuneri',
 'Mitglied',
 '▁Har',
 '▁Fix',
 '▁skate',
 'bücher',
 '▁AD',
 '▁WILL',
 '501',
 '303',
 '▁Awesome',
 '▁cohort',
 '▁Planet',
 '▁temp',
 '▁Functional',
 'gain',
 '▁emissions',
 '▁Fat',
 '122',
 '▁subway',
 '▁along',
 'Plus',
 '▁bride',
 '▁hustle',
 'working',
 '▁stroke',
 '▁lantern',
 'akh',
 'nvelop',
 '▁cultură',
 '▁erfolgen',
 'lining',
 '▁Devil',
 '▁executive',
 '▁Ven',
 '▁remains',
 'м',
 '▁ecran',
 '▁Emirates',
 '▁automatiquement',
 '▁flip',
 '▁avatar',
 '▁încălc',
 '▁bridge',
 'Set',
 '▁Kli',
 '▁Exist',
 '▁fair',
 '▁fields',
 'glob',
 '▁introdus',
 'gian',
 '▁Familien',
 '▁favorable',
 '▁femei',
 '▁shop',
 'offrir',
 'canceled',
 '▁Pra',
 'umfang',
 '▁Christchurch',
 '▁vis',
 '▁crunchy',
 '▁niece',
 'Vielen',
 '▁Dixon',
 '▁simultan',
 '▁substitute',
 '▁chair',
 '▁innovations',
 'Th',
 'ANA',
 '▁rai

In [15]:
extra_token = next(k for k,v in vocab.items() if "<extra_id_" in k)
extra_token

'<extra_id_94>'

In [16]:
vocab[extra_token]

32005

In [18]:
encoder.parameters()

<generator object Module.parameters at 0x73164baf92a0>

In [69]:
for param in encoder.parameters():
    param.requires_grad = False

In [40]:
encoder[0]._modules

OrderedDict([('auto_model',
              T5EncoderModel(
                (shared): Embedding(32128, 768)
                (encoder): T5Stack(
                  (embed_tokens): Embedding(32128, 768)
                  (block): ModuleList(
                    (0): T5Block(
                      (layer): ModuleList(
                        (0): T5LayerSelfAttention(
                          (SelfAttention): T5Attention(
                            (q): Linear(in_features=768, out_features=768, bias=False)
                            (k): Linear(in_features=768, out_features=768, bias=False)
                            (v): Linear(in_features=768, out_features=768, bias=False)
                            (o): Linear(in_features=768, out_features=768, bias=False)
                            (relative_attention_bias): Embedding(32, 12)
                          )
                          (layer_norm): T5LayerNorm()
                          (dropout): Dropout(p=0.1, inplace=False)
         

In [37]:
dir(encoder[0]._modules)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'move_to_end',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [72]:
encoder[0]._modules['auto_model']._modules['encoder']._modules['embed_tokens']._parameters['weight'].requires_grad = True

In [74]:
encoder[0]._modules['auto_model']._modules['encoder']._modules['embed_tokens']._parameters['weight'].requires_grad

True

In [73]:
encoder[0]._modules['auto_model']._modules['shared']._parameters['weight']

Parameter containing:
tensor([[ -0.7539,   0.5977,  -2.4375,  ...,   1.2500,  -0.7891,   3.5156],
        [  3.8125,  -0.8281,   5.1250,  ...,   2.5312,   3.9844,  -1.8516],
        [-10.6875,   7.2188, -24.3750,  ...,  14.0000,  23.7500,  22.1250],
        ...,
        [  2.2344,   6.7500, -11.0625,  ..., -11.3125,  13.5625,  16.6250],
        [  4.2500,   5.1250, -12.2500,  ..., -11.9375,  13.5000,  17.0000],
        [  4.0625,   6.9688, -12.2500,  ..., -11.3750,  11.9375,  16.6250]],
       device='cuda:0', requires_grad=True)

In [77]:
encoder[0]._modules['auto_model']._modules['encoder']._modules['embed_tokens']._parameters['weight']

Parameter containing:
tensor([[ -0.7539,   0.5977,  -2.4375,  ...,   1.2500,  -0.7891,   3.5156],
        [  3.8125,  -0.8281,   5.1250,  ...,   2.5312,   3.9844,  -1.8516],
        [-10.6875,   7.2188, -24.3750,  ...,  14.0000,  23.7500,  22.1250],
        ...,
        [  2.2344,   6.7500, -11.0625,  ..., -11.3125,  13.5625,  16.6250],
        [  4.2500,   5.1250, -12.2500,  ..., -11.9375,  13.5000,  17.0000],
        [  4.0625,   6.9688, -12.2500,  ..., -11.3750,  11.9375,  16.6250]],
       device='cuda:0', requires_grad=True)

In [82]:
import torch
input_ids = torch.tensor(enc_text).unsqueeze(0).to('cuda')
attention_mask = torch.ones_like(input_ids).to('cuda')
encoder({
            "input_ids": input_ids,
            "attention_mask": attention_mask,
        })["sentence_embedding"]

tensor([[ 1.6880e-02, -2.5375e-02,  1.4803e-02,  4.0549e-02,  1.0107e-02,
         -7.9545e-02, -3.7523e-02,  3.4453e-02,  6.1992e-02, -6.0965e-02,
          2.0597e-02, -2.9616e-02,  7.5119e-02,  3.5975e-02,  7.9790e-03,
          4.0681e-02,  4.6545e-02, -7.2806e-02,  2.5754e-02,  1.2182e-02,
          3.3701e-02, -3.0111e-02, -2.1208e-02,  1.6107e-02,  1.0413e-02,
         -1.9000e-02, -3.3100e-03, -4.3731e-02,  3.8579e-02, -1.6012e-02,
          4.1239e-02, -7.2232e-02,  2.9509e-02,  8.4396e-02, -4.7896e-03,
          2.6078e-02, -2.0030e-02, -1.0783e-02, -3.1870e-02,  2.0912e-02,
         -2.5652e-02, -4.9334e-02, -1.2952e-02,  2.0291e-02, -8.2728e-02,
         -4.9955e-02,  1.3028e-02,  1.2655e-02, -1.9449e-02, -5.5205e-02,
         -4.4985e-02,  1.4496e-02, -1.1964e-02, -5.9941e-03, -9.6805e-03,
          7.6495e-03, -5.3963e-02,  1.9213e-02,  1.8903e-02, -5.2849e-02,
         -7.2740e-02,  3.8133e-02, -3.7457e-02,  7.1183e-03, -7.8619e-03,
          2.9347e-02, -8.2039e-02, -1.

In [83]:
encoder[0]._modules['auto_model']._modules['encoder']._modules['embed_tokens']._parameters['weight'].grad